### ISSUE TITLE
GIT_BASE_URL throws an error even when specified in the config dictionary parameter

### ISSUE THREAD

**Issue by fuzzball81** [release-depot/flask-container-scaffold#23]
`app = AppScaffold(config={'GIT_BASE_URL': ''}).app`

Throws the following error:
```
Traceback (most recent call last):
...
  File "~/virtualenvs/dlrn-X98Lxlfh/lib/python3.9/site-packages/flask_container_scaffold/app_scaffold.py", line 28, in __init__
    self._init_app()
  File "~/virtualenvs/dlrn-X98Lxlfh/lib/python3.9/site-packages/flask_container_scaffold/app_scaffold.py", line 32, in _init_app
    self._configure_app()
  File "~/virtualenvs/dlrn-X98Lxlfh/lib/python3.9/site-packages/flask_container_scaffold/app_scaffold.py", line 59, in _configure_app
    self.setup_core_config_from_env(verify=True)
  File "~/virtualenvs/dlrn-X98Lxlfh/lib/python3.9/site-packages/flask_container_scaffold/app_scaffold.py", line 77, in setup_core_config_from_env
    raise ValueError(f"No {i} set for Flask application")
ValueError: No GIT_BASE_URL set for Flask application
```

`GIT_BASE_URL` seems to be required to use the library but is not documented or defined how it being used.

**Comment by jguiditta** [comment]
Sorry for the confusion, this _was_ previously required before my last patch, which made flask-container-scaffold more flexible so it is no longer required, but I have not yet tagged a new release.  The docs here represent the latest master rather than the latest pypi release. Now that I am back from holiday break, I will go over the state of things here and get a new release out shortly, hopefully by end of week.
